export const ActionTypes = {
    LOGIN: "LOGIN",
    REGISTER: "REGISTER",
    LOGOUT: "LOGOUT",
    GETALLITEM: "GETALLITEM",
    ADDITEM: "ADDITEM",
    EDITITEM: "EDITITEM",
    REMOVEITEM:"REMOVEITEM",
    GETHOME : "GETHOME",
}

